[Docs/Chore] #211 README 수정, REST API 설계에 맞게 엔드포인트 수정
DaeChamSa/with-the-developer pull request #214
Opened 2024-10-07 09:01 UTC by JungUiJin

2024-10-07 09:57 UTC, hyomee2 commented on back-end/with-the-developer/src/main/java/com/developer/user/command/application/controller/UserCommandController.java
>      // 알림 수신 여부 허용
수신여부 허용, 해제 합쳐서 restful하게 바꿔주시면 감사하겠습니다~~~

2024-10-07 11:12 UTC, PBEM22 submitted a review, later dismissed

2024-10-07 14:00 UTC, we4sley commented on back-end/with-the-developer/src/main/java/com/developer/goods/command/application/controller/GoodsController.java
> +@RequestMapping("goods")
/ 어디갔나요

2024-10-07 14:00 UTC, we4sley commented on back-end/with-the-developer/src/main/java/com/developer/goods/command/application/controller/GoodsController.java
> +    @DeleteMapping("{goodsCode}")
얘도

2024-10-07 14:04 UTC, PBEM22 approved these changes, later dismissed

2024-10-07 14:10 UTC, JungUiJin commented on back-end/with-the-developer/src/main/java/com/developer/goods/command/application/controller/GoodsController.java
> +@RequestMapping("goods")
굿즈 도메인 안에 있고  단순 등록이라고 생각해서 지웠는데 넣는게 나을까요

2024-10-07 14:16 UTC, we4sley approved these changes

2024-10-07 23:00 UTC, PBEM22 submitted a review, later dismissed
확인했습니다

2024-10-07 23:53 UTC, we4sley requested changes
비회원 조회 엔드포인트 변경

2024-10-10 03:30 UTC, we4sley approved these changes, later dismissed

2024-10-10 06:36 UTC, hyomee2 approved these changes, later dismissed

2024-10-10 06:41 UTC, we4sley approved these changes

2024-10-10 06:41 UTC, hyomee2 approved these changes

2024-10-10 06:42 UTC, merged